### ISSUE TITLE
Merge multiple inputs

### ISSUE THREAD

**Issue by niggiover9000** [Hundemeier/sacn#10]
Hey there!
First of all, a big thank you for your awesome library! 

I am trying to use multiple inputs, for example a lighning console and a house light control panel. This causes flickering, because the packages are received succcesively and not merged together. Do you have an idea how I could build a workaround?

Thanks in advance!

**Comment by Hundemeier** [comment]
Sorry for the late reply.
Merging is not in the scope of sACN and therefore is not supported by this library directly. If two senders send different data with the same priority and universe to a receiver of this library, the behaviour is basically undefined (flickering due to fast changing of the DMX values).
To create a merge, you would need to send out the values on two different universes and receive both with your script. Then you can implement your own merging.

**Comment by niggiover9000** [comment]
Hey there,

in the meantime, I managed to write a merging algorithm for my project. It can handle sources with different priority, sources with same priority, special packets from ETC consoles with per-channel-priority and you can switch von HTP to LTP mode
If you are interested, have a look at it here: https://github.com/niggiover9000/sACNtoArtNet
